spring.datasource.url=jdbc:postgresql://amazonaws.cf8u6owg2zid.eu-west-2.rds.amazonaws.com:5432/record
spring.datasource.username=postgres
spring.datasource.password=postgres13
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show-sql=true
spring.jpa.hibernate.ddl-auto=update
s